name: Nicholas Sardo, Polyglot Software Engineer
markdown: Kramdown
permalink: /blog/:year/:month/:day/:title
url: nsardo.github.io
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-include-cache
github: [metadata] 
encoding: UTF-8 